/**
 * APIMATICCodeGenLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const Format = {

    /**
     * TODO: Write general description for this element
     */
    ENUM_API_BLUEPRINT: 'API Blueprint',

    /**
     * TODO: Write general description for this element
     */
    ENUM_GOOGLE_DISCOVERY: 'Google Discovery',

    /**
     * TODO: Write general description for this element
     */
    RAML: 'RAML',

    /**
     * TODO: Write general description for this element
     */
    WADL: 'WADL',

    /**
     * TODO: Write general description for this element
     */
    SWAGGER: 'Swagger',

    /**
     * TODO: Write general description for this element
     */
    ENUM_IO_DOCS: 'IO Docs',

    /**
     * TODO: Write general description for this element
     */
    APIMATIC: 'APIMATIC',

    /**
     * TODO: Write general description for this element
     */
    WSDL: 'WSDL',

    /**
     * TODO: Write general description for this element
     */
    MASHAPE: 'Mashape',

    /**
     * TODO: Write general description for this element
     */
    POSTMAN: 'Postman',

    /**
     * TODO: Write general description for this element
     */
    HAR: 'HAR',

    /**
     * TODO: Write general description for this element
     */
    OPEN_API_SPEC_300_RC_1: 'OpenApi3',

};

module.exports = Format;
