/**
 * APIMATICCodeGenLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const Template = {

    /**
     * TODO: Write general description for this element
     */
    CS_PORTABLE_NET_LIB: 'cs_portable_net_lib',

    /**
     * TODO: Write general description for this element
     */
    JAVA_ECLIPSE_JRE_LIB: 'java_eclipse_jre_lib',

    /**
     * TODO: Write general description for this element
     */
    JAVA_GRADLE_ANDROID_LIB: 'java_gradle_android_lib',

    /**
     * TODO: Write general description for this element
     */
    OBJC_COCOA_TOUCH_IOS_LIB: 'objc_cocoa_touch_ios_lib',

    /**
     * TODO: Write general description for this element
     */
    ANGULAR_JAVASCRIPT_LIB: 'angular_javascript_lib',

    /**
     * TODO: Write general description for this element
     */
    RUBY_GENERIC_LIB: 'ruby_generic_lib',

    /**
     * TODO: Write general description for this element
     */
    ENUM_PYTHON_GENERIC_LIB: 'python_generic_lib ￼',

    /**
     * TODO: Write general description for this element
     */
    ENUM_PHP_GENERIC_LIB: 'php_generic_lib ￼',

    /**
     * TODO: Write general description for this element
     */
    ENUM_NODE_JAVASCRIPT_LIB: 'node_javascript_lib ￼',

    /**
     * TODO: Write general description for this element
     */
    ENUM_GO_GENERIC_LIB: 'go_generic_lib ￼',

};

module.exports = Template;
