/**
 * APIMATICCodeGenLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of ValidateAnAPIDescriptionResponse
 */
class ValidateAnAPIDescriptionResponse extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.errors = this.constructor.getValue(obj.errors || obj.Errors);
        this.warnings = this.constructor.getValue(obj.warnings || obj.Warnings);
        this.messages = this.constructor.getValue(obj.messages || obj.Messages);
        this.success = this.constructor.getValue(obj.success || obj.Success);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'errors', realName: 'Errors', array: true },
            { name: 'warnings', realName: 'Warnings', array: true },
            { name: 'messages', realName: 'Messages', array: true },
            { name: 'success', realName: 'Success' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = ValidateAnAPIDescriptionResponse;
